version: '3.7'

# minio server's web interface will be accessible on the host at port 9001
services:
  minio:
    image: minio/minio:RELEASE.2020-03-19T21-49-00Z
    volumes:
      - shops-data:/data/shops
      - articles-data:/data/articles
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  db:
    image: postgres:12.2-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

  db-ui:
    image: dpage/pgadmin4:4.19
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - 80:8080

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  shops-data:
  articles-data:
  postgres:
  pgadmin:
