version: '3.7'

services:
  lieferemma-backend:
    image: lieferemma/backend:latest
    environment:
      GRPC_API_ADDR: 0.0.0.0:50051
      DATABASE_URL: postgres://postgres:changeme@localhost/lieferemma
    ports:
      - "50051:50051"
    networks:
      - postgres

  minio:
    image: minio/minio:RELEASE.2020-03-19T21-49-00Z
    volumes:
      - shops-data:/data/shops
      - articles-data:/data/articles
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    networks:
      - minio
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  postgres:
    container_name: postgres_container
    image: nickblah/postgis:12.2-postgis-3.0.0
    environment:
      POSTGRES_DB: lieferemma
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:4.19
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  minio:
    driver: bridge


## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  shops-data:
  articles-data:
  postgres:
  pgadmin:
